name: SurvivalGamesV3
main: SurvivalGamesV3\SurvivalGamesV3
version: 3.0.1
api: 
- 1.0.0
- 1.1.0
- 2.0.0
author: 


commands:
    sg:
        usage: /sg make
        description: SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands
