name: SurvivalGamesV2
main: SurvivalGamesV2\SurvivalGamesV2
version: 2.0.8
api: 
- 1.0.0
- 1.1.0
- 2.0.0
author: 


commands:
    sg:
        usage: /sg make
        description: SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands
