name: SurvivalGamesV2
main: SurvivalGamesV2\SurvivalGamesV2
version: 1.0.0
api: 1.1.0
author: 


commands:
    sg:
        usage: /sg
        description: SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands